version: '3.7'
services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      menlock:
        soft: -1
        hard: -1

    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.13.4
    environment:
      - ELASTICSERACH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.13.4
    ports: 
      - '5000:5000'
    volumes: 
      - type: bind
        source: ./logstash_pipeline/
        target: /usr/share/logstash/pipeline
        read_only: true
    environment:
      - http.host: "0.0.0.0"
      - xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]

volumes:
  elasticsearch-data:
    driver: local

